### ISSUE TITLE
QEMU Bug in Buildkit 0.10.6

### ISSUE THREAD

**Issue by samuelattwood** [depot/machine-images#6]
Hey @jacobwgillespie

There appears to be a bug in the version of user-mode QEMU used by Buildkit 0.10.6, it causes issue with certain binaries, the ones we ran across are `dpkg-split` and `dpkg-deb`.

You can easily reproduce the issue with
```
depot build --build-platform "linux/amd64" --platform "linux/arm64,linux/amd64" .
```
Dockerfile
```Dockerfile
#syntax=docker/dockerfile-upstream:1.4
FROM ubuntu:latest

RUN apt-get update && apt-get install -y apache2
```

I reproduced with just a buildctl command and the issue was resolved when I bumped buildkit to the latest, currently `0.11.2`, so it should be as simple as bumping the version in your `provision.sh`. Thanks!

https://github.com/depot/machine-images/blob/ca07146485635385baddf83d0f13b3326a9e2b18/buildkit/provision.sh#L28

**Comment by jacobwgillespie** [comment]
Hey, thanks for this! BuildKit was on our plan for next week anyways, so nice to hear that may fix the QEMU issue as well 👍 

Here's a PR: #7. I'll ping back here once it's deployed to the live builders.

We've been watching the rollout of BuildKit 0.11.x and buildx 0.10.x - there's an open issue where buildx changed the default behavior to always generate provenance attestations, which in turn always generates manifest lists, which aren't supported by platforms like AWS Lambda or Google Cloud Run: https://github.com/docker/buildx/issues/1533. 

I _think_ that change to enable them by default was made inside buildx, so we should be able to work around it in the Depot CLI, but I'll need to verify that the change isn't actually inside BuildKit, so that #7 doesn't break builds. 🙂

**Comment by jacobwgillespie** [comment]
Hey! 👋 

This has been deployed to all Depot builders and appears to fix the QEMU bug - let me know if it's working for you!

**Comment by samuelattwood** [comment]
Hey @jacobwgillespie, looks good to me as well. Thanks very much!
